package com.example.data.repository

import com.example.data.local.dao.HomeManagementDao
import com.example.data.local.entity.ApplianceCleanRoutine
import com.example.data.local.entity.ChoreItem
import com.example.data.local.entity.GardenCalendarItem
import com.example.data.local.entity.GuestChecklistItem
import com.example.data.local.entity.KidsShoppingItem
import com.example.data.local.entity.LivingCleaningTask
import com.example.data.local.entity.MaintenanceItem
import com.example.data.local.entity.MealPlanItem
import com.example.data.local.entity.PantryItem
import com.example.data.local.entity.PersonalRoutineItem
import com.example.data.local.entity.PlantCareItem
import com.example.data.local.entity.SmartShoppingItem
import com.example.data.local.entity.SpaceDeclutterItem
import com.example.data.local.entity.StudyTask
import com.example.data.local.entity.ToolItem
import com.example.data.local.entity.WardrobeItem
import kotlinx.coroutines.flow.Flow

class HomeRepository(private val dao: HomeManagementDao) {

    // Kitchen
    val allPantryItems: Flow<List<PantryItem>> = dao.getAllPantryItems()
    val allShoppingItems: Flow<List<SmartShoppingItem>> = dao.getAllShoppingItems()
    val allMealPlans: Flow<List<MealPlanItem>> = dao.getAllMealPlans()
    val allApplianceCleanRoutines: Flow<List<ApplianceCleanRoutine>> = dao.getAllApplianceCleanRoutines()

    suspend fun addPantryItem(item: PantryItem) {
        dao.insertPantryItem(item)
        if (item.isLowStock) {
            dao.insertShoppingItem(
                SmartShoppingItem(
                    itemName = item.name,
                    quantity = "۱ ${item.unit}",
                    category = item.category,
                    isBought = false,
                    isAutoGenerated = true,
                    addedFromRoom = "Kitchen"
                )
            )
        }
    }

    suspend fun deletePantryItem(id: Long) = dao.deletePantryItem(id)

    suspend fun addShoppingItem(item: SmartShoppingItem) = dao.insertShoppingItem(item)
    suspend fun toggleShoppingItem(item: SmartShoppingItem) = dao.updateShoppingItem(item.copy(isBought = !item.isBought))
    suspend fun deleteShoppingItem(id: Long) = dao.deleteShoppingItem(id)

    suspend fun addMealPlan(item: MealPlanItem) = dao.insertMealPlan(item)
    suspend fun deleteMealPlan(id: Long) = dao.deleteMealPlan(id)

    suspend fun toggleApplianceClean(routine: ApplianceCleanRoutine) {
        val updated = routine.copy(
            isCompleted = !routine.isCompleted,
            daysRemaining = if (!routine.isCompleted) routine.frequencyDays else 0
        )
        dao.updateApplianceCleanRoutine(updated)
    }
    suspend fun addApplianceRoutine(routine: ApplianceCleanRoutine) = dao.insertApplianceCleanRoutine(routine)

    // Living Room
    val allLivingCleaningTasks: Flow<List<LivingCleaningTask>> = dao.getAllLivingCleaningTasks()
    val allPlants: Flow<List<PlantCareItem>> = dao.getAllPlants()
    val allGuestChecklist: Flow<List<GuestChecklistItem>> = dao.getAllGuestChecklist()

    suspend fun toggleLivingCleaningTask(task: LivingCleaningTask) = dao.updateLivingCleaningTask(task.copy(isDone = !task.isDone))
    suspend fun addLivingCleaningTask(task: LivingCleaningTask) = dao.insertLivingCleaningTask(task)
    suspend fun deleteLivingCleaningTask(id: Long) = dao.deleteLivingCleaningTask(id)

    suspend fun waterPlant(plant: PlantCareItem) = dao.updatePlant(plant.copy(daysUntilWatering = plant.waterIntervalDays))
    suspend fun togglePlantLeafClean(plant: PlantCareItem) = dao.updatePlant(plant.copy(needsLeafCleaning = !plant.needsLeafCleaning))
    suspend fun togglePlantFertilizer(plant: PlantCareItem) = dao.updatePlant(plant.copy(needsFertilizer = !plant.needsFertilizer))
    suspend fun addPlant(plant: PlantCareItem) = dao.insertPlant(plant)

    suspend fun toggleGuestChecklist(item: GuestChecklistItem) = dao.updateGuestChecklist(item.copy(isDone = !item.isDone))
    suspend fun addGuestChecklistItem(item: GuestChecklistItem) = dao.insertGuestChecklist(item)

    // Bedroom
    val allWardrobeItems: Flow<List<WardrobeItem>> = dao.getAllWardrobeItems()
    val allPersonalRoutines: Flow<List<PersonalRoutineItem>> = dao.getAllPersonalRoutines()
    val allDeclutterItems: Flow<List<SpaceDeclutterItem>> = dao.getAllDeclutterItems()

    suspend fun toggleWardrobeItem(item: WardrobeItem) = dao.updateWardrobeItem(item.copy(isDone = !item.isDone))
    suspend fun addWardrobeItem(item: WardrobeItem) = dao.insertWardrobeItem(item)

    suspend fun togglePersonalRoutine(routine: PersonalRoutineItem) {
        val newDone = !routine.isDoneToday
        val newStreak = if (newDone) routine.streakDays + 1 else maxOf(0, routine.streakDays - 1)
        dao.updatePersonalRoutine(routine.copy(isDoneToday = newDone, streakDays = newStreak))
    }
    suspend fun addPersonalRoutine(routine: PersonalRoutineItem) = dao.insertPersonalRoutine(routine)

    suspend fun toggleDeclutterItem(item: SpaceDeclutterItem) = dao.updateDeclutterItem(item.copy(isOrganized = !item.isOrganized))
    suspend fun addDeclutterItem(item: SpaceDeclutterItem) = dao.insertDeclutterItem(item)

    // Kids Room
    val allChores: Flow<List<ChoreItem>> = dao.getAllChores()
    val allStudyTasks: Flow<List<StudyTask>> = dao.getAllStudyTasks()
    val allKidsShopping: Flow<List<KidsShoppingItem>> = dao.getAllKidsShopping()

    suspend fun toggleChore(chore: ChoreItem) = dao.updateChore(chore.copy(isCompleted = !chore.isCompleted))
    suspend fun addChore(chore: ChoreItem) = dao.insertChore(chore)

    suspend fun toggleStudyTask(task: StudyTask) = dao.updateStudyTask(task.copy(isFinished = !task.isFinished))
    suspend fun addStudyTask(task: StudyTask) = dao.insertStudyTask(task)

    suspend fun toggleKidsShopping(item: KidsShoppingItem) = dao.updateKidsShopping(item.copy(isPurchased = !item.isPurchased))
    suspend fun addKidsShopping(item: KidsShoppingItem) = dao.insertKidsShopping(item)

    // Yard & Outdoors
    val allGardenTasks: Flow<List<GardenCalendarItem>> = dao.getAllGardenTasks()
    val allMaintenanceItems: Flow<List<MaintenanceItem>> = dao.getAllMaintenanceItems()
    val allTools: Flow<List<ToolItem>> = dao.getAllTools()

    suspend fun toggleGardenTask(task: GardenCalendarItem) = dao.updateGardenTask(task.copy(isDone = !task.isDone))
    suspend fun addGardenTask(task: GardenCalendarItem) = dao.insertGardenTask(task)

    suspend fun toggleMaintenanceItem(item: MaintenanceItem) = dao.updateMaintenanceItem(item.copy(isDone = !item.isDone))
    suspend fun addMaintenanceItem(item: MaintenanceItem) = dao.insertMaintenanceItem(item)

    suspend fun toggleToolAvailability(tool: ToolItem) = dao.updateTool(tool.copy(isAvailable = !tool.isAvailable))
    suspend fun addTool(tool: ToolItem) = dao.insertTool(tool)
}
