package com.example.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "pantry_items")
data class PantryItem(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val category: String, // Fridge, Pantry, Freezer, Spice
    val quantity: Double,
    val unit: String, // kg, pcs, liters, pack
    val expiryDaysLeft: Int,
    val isLowStock: Boolean = false,
    val storageLocation: String = "یخچال"
)

@Entity(tableName = "smart_shopping_items")
data class SmartShoppingItem(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val itemName: String,
    val quantity: String = "۱ عدد",
    val category: String = "آشپزخانه",
    val isBought: Boolean = false,
    val isAutoGenerated: Boolean = false,
    val addedFromRoom: String = "Kitchen"
)

@Entity(tableName = "meal_plan_items")
data class MealPlanItem(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val dayOfWeek: String, // شنبه, یکشنبه, ...
    val mealType: String, // صبحانه, ناهار, شام
    val recipeTitle: String,
    val prepTimeMinutes: Int = 30,
    val notes: String = ""
)

@Entity(tableName = "appliance_clean_routines")
data class ApplianceCleanRoutine(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val applianceName: String, // یخ‌زدایی یخچال، فیلتر هود، تمیزکاری هواپز
    val frequencyDays: Int = 30,
    val daysRemaining: Int = 10,
    val lastCleanedDate: String = "۲ هفته پیش",
    val isCompleted: Boolean = false
)
