package com.example.data.local

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase
import com.example.data.local.dao.HomeManagementDao
import com.example.data.local.entity.ApplianceCleanRoutine
import com.example.data.local.entity.ChoreItem
import com.example.data.local.entity.GardenCalendarItem
import com.example.data.local.entity.GuestChecklistItem
import com.example.data.local.entity.KidsShoppingItem
import com.example.data.local.entity.LivingCleaningTask
import com.example.data.local.entity.MaintenanceItem
import com.example.data.local.entity.MealPlanItem
import com.example.data.local.entity.PantryItem
import com.example.data.local.entity.PersonalRoutineItem
import com.example.data.local.entity.PlantCareItem
import com.example.data.local.entity.SmartShoppingItem
import com.example.data.local.entity.SpaceDeclutterItem
import com.example.data.local.entity.StudyTask
import com.example.data.local.entity.ToolItem
import com.example.data.local.entity.WardrobeItem
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

@Database(
    entities = [
        PantryItem::class,
        SmartShoppingItem::class,
        MealPlanItem::class,
        ApplianceCleanRoutine::class,
        LivingCleaningTask::class,
        PlantCareItem::class,
        GuestChecklistItem::class,
        WardrobeItem::class,
        PersonalRoutineItem::class,
        SpaceDeclutterItem::class,
        ChoreItem::class,
        StudyTask::class,
        KidsShoppingItem::class,
        GardenCalendarItem::class,
        MaintenanceItem::class,
        ToolItem::class
    ],
    version = 1,
    exportSchema = false
)
abstract class AppDatabase : RoomDatabase() {

    abstract fun homeManagementDao(): HomeManagementDao

    companion object {
        @Volatile
        private var INSTANCE: AppDatabase? = null

        fun getDatabase(context: Context, scope: CoroutineScope? = null): AppDatabase {
            return INSTANCE ?: synchronized(this) {
                val builder = Room.databaseBuilder(
                    context.applicationContext,
                    AppDatabase::class.java,
                    "home_management_database"
                )
                if (scope != null) {
                    builder.addCallback(DatabaseCallback(scope))
                }
                val instance = builder
                    .fallbackToDestructiveMigration(false)
                    .build()
                INSTANCE = instance
                instance
            }
        }

        private class DatabaseCallback(
            private val scope: CoroutineScope
        ) : RoomDatabase.Callback() {
            override fun onCreate(db: SupportSQLiteDatabase) {
                super.onCreate(db)
                INSTANCE?.let { database ->
                    scope.launch(Dispatchers.IO) {
                        populateInitialData(database.homeManagementDao())
                    }
                }
            }

            private suspend fun populateInitialData(dao: HomeManagementDao) {
                // Kitchen Pantry
                dao.insertPantryItem(PantryItem(name = "شیر کم‌چرب", category = "لبنیات", quantity = 1.0, unit = "بطری", expiryDaysLeft = 2, isLowStock = false, storageLocation = "یخچال"))
                dao.insertPantryItem(PantryItem(name = "روغن زیتون فرابکر", category = "کابینت", quantity = 0.2, unit = "لیتر", expiryDaysLeft = 180, isLowStock = true, storageLocation = "کابینت ادویه"))
                dao.insertPantryItem(PantryItem(name = "تخم مرغ", category = "یخچال", quantity = 4.0, unit = "عدد", expiryDaysLeft = 8, isLowStock = true, storageLocation = "درب یخچال"))
                dao.insertPantryItem(PantryItem(name = "پنیر فتا", category = "لبنیات", quantity = 1.0, unit = "بسته", expiryDaysLeft = 14, isLowStock = false, storageLocation = "طبقه میانی"))
                dao.insertPantryItem(PantryItem(name = "نان تست سبوس‌دار", category = "نان", quantity = 0.5, unit = "بسته", expiryDaysLeft = 3, isLowStock = false, storageLocation = "سبد نان"))

                // Kitchen Shopping
                dao.insertShoppingItem(SmartShoppingItem(itemName = "روغن زیتون", quantity = "۱ بطری", category = "خواروبار", isBought = false, isAutoGenerated = true, addedFromRoom = "Kitchen"))
                dao.insertShoppingItem(SmartShoppingItem(itemName = "تخم مرغ محلی", quantity = "۱ شانه", category = "پروتئین", isBought = false, isAutoGenerated = true, addedFromRoom = "Kitchen"))
                dao.insertShoppingItem(SmartShoppingItem(itemName = "پیاز قرمز و سیب‌زمینی", quantity = "۲ کیلو", category = "تره‌بار", isBought = true, isAutoGenerated = false, addedFromRoom = "Kitchen"))

                // Kitchen Meals
                dao.insertMealPlan(MealPlanItem(dayOfWeek = "شنبه", mealType = "ناهار", recipeTitle = "قورمه‌سبزی جاافتاده با برنج زعفرانی", prepTimeMinutes = 90, notes = "لوبیا از شب قبل خیسانده شود"))
                dao.insertMealPlan(MealPlanItem(dayOfWeek = "یکشنبه", mealType = "شام", recipeTitle = "سوپ جو و سالاد سبزیجات تازه", prepTimeMinutes = 40, notes = "غذای سبک بعد از ورزش"))
                dao.insertMealPlan(MealPlanItem(dayOfWeek = "دوشنبه", mealType = "ناهار", recipeTitle = "زرشک‌پلو با مرغ مجلسی", prepTimeMinutes = 60, notes = "زرشک با شکر و خلال پسته تفت داده شود"))
                dao.insertMealPlan(MealPlanItem(dayOfWeek = "سه‌شنبه", mealType = "شام", recipeTitle = "کوکو سبزی با گردو و زرشک", prepTimeMinutes = 30, notes = "سبزی تازه معطر"))

                // Kitchen Appliance Clean Routines
                dao.insertApplianceCleanRoutine(ApplianceCleanRoutine(applianceName = "رسوب‌زدایی و تمیزکاری سرخ‌کن بدون روغن (هواپز)", frequencyDays = 14, daysRemaining = 2, lastCleanedDate = "۱۲ روز پیش", isCompleted = false))
                dao.insertApplianceCleanRoutine(ApplianceCleanRoutine(applianceName = "شستشوی فیلتر آلومینیومی هود آشپزخانه", frequencyDays = 30, daysRemaining = 8, lastCleanedDate = "۳ هفته پیش", isCompleted = false))
                dao.insertApplianceCleanRoutine(ApplianceCleanRoutine(applianceName = "یخ‌زدایی و تمیز کردن کشوهای فریزر", frequencyDays = 60, daysRemaining = 25, lastCleanedDate = "۱ ماه پیش", isCompleted = false))

                // Living Room Cleaning
                dao.insertLivingCleaningTask(LivingCleaningTask(title = "جاروبرقی کامل فرش‌ها و زیر مبل‌ها", frequency = "روزانه", isDone = false, estimatedMinutes = 20))
                dao.insertLivingCleaningTask(LivingCleaningTask(title = "تی کشیدن پارکت و سرامیک سالن", frequency = "هفتگی", isDone = true, estimatedMinutes = 15))
                dao.insertLivingCleaningTask(LivingCleaningTask(title = "گردگیری میز تلویزیون و قفسه کتابخانه", frequency = "هفتگی", isDone = false, estimatedMinutes = 10))

                // Plants
                dao.insertPlant(PlantCareItem(plantName = "مونسترا (برگ انجیری)", location = "گوشه نورگیر سالن", waterIntervalDays = 5, daysUntilWatering = 1, needsFertilizer = true, needsLeafCleaning = true, sunlightLevel = "نور فیلتر شده"))
                dao.insertPlant(PlantCareItem(plantName = "سانسوریا ابلق", location = "کنار کنسول ورودی", waterIntervalDays = 12, daysUntilWatering = 6, needsFertilizer = false, needsLeafCleaning = false, sunlightLevel = "کم‌نور و مقاوم"))
                dao.insertPlant(PlantCareItem(plantName = "پتوس مرمری آویز", location = "روی شلف دیواری", waterIntervalDays = 6, daysUntilWatering = 3, needsFertilizer = false, needsLeafCleaning = true, sunlightLevel = "نور ملایم"))

                // Guest Checklist
                dao.insertGuestChecklist(GuestChecklistItem(taskTitle = "آماده‌سازی حوله دست و صابون معطر مهمان", category = "تدارکات", isDone = false))
                dao.insertGuestChecklist(GuestChecklistItem(taskTitle = "خرید میوه فصل و آماده کردن شیرینی تازه", category = "پذیرایی", isDone = false))
                dao.insertGuestChecklist(GuestChecklistItem(taskTitle = "خالی کردن جالباسی ورودی و قرار دادن دمپایی روفرشی", category = "نظافت و نظم", isDone = true))

                // Bedroom
                dao.insertWardrobeItem(WardrobeItem(title = "پالتوها و کاپشن‌های ضخیم زمستانی", season = "پاییزه/زمستانه", careType = "ارسال به خشکشویی", nextScheduleDate = "پایان ماه", isDone = false))
                dao.insertWardrobeItem(WardrobeItem(title = "تعویض و شستشوی روتختی و روبالشتی‌ها", season = "روتین دوره‌ای", careType = "ماشین لباسشویی ۶۰ درجه", nextScheduleDate = "پنج‌شنبه", isDone = true))
                dao.insertPersonalRoutine(PersonalRoutineItem(title = "مرتب کردن تخت خواب بلافاصله بعد بیداری", timeOfDay = "صبح", streakDays = 7, isDoneToday = true))
                dao.insertPersonalRoutine(PersonalRoutineItem(title = "تهویه هوای اتاق خواب (باز کردن ۱۰ دقیقه‌ای پنجره)", timeOfDay = "صبح", streakDays = 5, isDoneToday = false))
                dao.insertPersonalRoutine(PersonalRoutineItem(title = "آماده‌سازی لباس‌های کار فردای کاری", timeOfDay = "شب", streakDays = 4, isDoneToday = false))
                dao.insertDeclutterItem(SpaceDeclutterItem(areaName = "کشوهای دراور لباس زیر و جوراب", priority = "بالا", isOrganized = false, reminderNotes = "استفاده از جداکننده ارگانایزر"))
                dao.insertDeclutterItem(SpaceDeclutterItem(areaName = "میز آرایش و ساماندهی عطرها", priority = "متوسط", isOrganized = true, reminderNotes = "گردگیری شیشه‌ها"))

                // Kids Room
                dao.insertChore(ChoreItem(title = "جمع‌آوری اسباب‌بازی‌ها و لگوها داخل باکس", childName = "آرتین", rewardPoints = 20, isCompleted = false, emoji = "🧸"))
                dao.insertChore(ChoreItem(title = "مرتب کردن میز تحریر بعد از تکالیف", childName = "آرتین", rewardPoints = 15, isCompleted = true, emoji = "📚"))
                dao.insertChore(ChoreItem(title = "مسواک زدن قبل از خواب شبانه", childName = "آرتین", rewardPoints = 10, isCompleted = false, emoji = "✨"))
                dao.insertStudyTask(StudyTask(subject = "ریاضی", taskDescription = "تمرین جدول ضرب و حل مسئله صفحه ۵۸", dueDate = "دوشنبه عصر", isFinished = false))
                dao.insertStudyTask(StudyTask(subject = "علوم", taskDescription = "کاشت لوبیا و ثبت روند رشد در دفترچه", dueDate = "پایان هفته", isFinished = true))
                dao.insertKidsShopping(KidsShoppingItem(itemName = "ماژیک هایلایتر ۴ رنگ", category = "لوازم‌التحریر", childName = "آرتین", isPurchased = false))
                dao.insertKidsShopping(KidsShoppingItem(itemName = "کتونی ورزشی زنگ ورزش", category = "پوشاک", childName = "آرتین", isPurchased = false))

                // Yard & Outdoors
                dao.insertGardenTask(GardenCalendarItem(taskTitle = "هرس شاخه‌های خشک درختان میوه", targetAreaOrPlant = "درختان حیاط پشتی", seasonTag = "بهار", scheduledDate = "هفته دوم فروردین", isDone = false))
                dao.insertGardenTask(GardenCalendarItem(taskTitle = "سمپاشی پیشگیرانه رزها و شته‌زدایی", targetAreaOrPlant = "باغچه گل سرخ", seasonTag = "بهار", scheduledDate = "اواخر فروردین", isDone = false))
                dao.insertGardenTask(GardenCalendarItem(taskTitle = "کوددهی هیومیک اسید و تقویت چمن", targetAreaOrPlant = "فضای سبز وسط", seasonTag = "بهار", scheduledDate = "اردیبهشت", isDone = true))
                dao.insertMaintenanceItem(MaintenanceItem(title = "پاکسازی برگ‌ها و رسوبات ناودان‌ها", frequencyLabel = "فصلی", statusText = "قبل از بارندگی پاییز و بهار", isDone = false))
                dao.insertMaintenanceItem(MaintenanceItem(title = "بررسی سلامت لامپ‌ها و سنسور چشمی حیاط", frequencyLabel = "ماهانه", statusText = "سالم و روشن", isDone = true))
                dao.insertMaintenanceItem(MaintenanceItem(title = "رنگ‌آمیزی ضدزنگ نرده‌ها و درب ورودی", frequencyLabel = "سالانه", statusText = "برنامه‌ریزی برای تابستان", isDone = false))
                dao.insertTool(ToolItem(toolName = "قیچی باغبانی شاخه‌زن", storageLocation = "قفسه B انبار حیاط", category = "باغبانی", isAvailable = true))
                dao.insertTool(ToolItem(toolName = "دریل چکشی و جعبه مته", storageLocation = "کابینت فلزی کارگاه", category = "فنی", isAvailable = true))
                dao.insertTool(ToolItem(toolName = "شیلنگ جمع‌کن ۵۰ متری با سری مه‌پاش", storageLocation = "کنار شیر آب حیاط", category = "باغبانی", isAvailable = true))
            }
        }
    }
}
